# ------------------------------------------------------------
# 1. Universe and executable
# ------------------------------------------------------------
universe = vanilla
executable = scripts/run_geant4.sh

# ------------------------------------------------------------
# 2. Logging
# ------------------------------------------------------------
log = output/logs/job-$(Cluster)-$(Process).log
output = output/logs/job-$(Cluster)-$(Process)_$(part_type)-$(ion_z)-$(ion_a)_$(energy_val)-$(energy_unit)_$(physics)_$(geometry)_$(geometry_method)_$(voxel_val)-$(voxel_unit).out
error  = output/logs/job-$(Cluster)-$(Process)_$(part_type)-$(ion_z)-$(ion_a)_$(energy_val)-$(energy_unit)_$(physics)_$(geometry)_$(geometry_method)_$(voxel_val)-$(voxel_unit).err

# ------------------------------------------------------------
# 3. Arguments (make sure the script expects these)
# ------------------------------------------------------------
arguments = "$(physics) $(part_type) $(ion_z) $(ion_a) $(ion_q) $(energy_val) $(energy_unit) $(beam_on) $(geometry) $(geometry_method) $(voxel_val) $(voxel_unit) $(cpus) $(memory) $(disk) $(Cluster)_$(Process)"

# ------------------------------------------------------------
# 4. Environment Forwarding
# ------------------------------------------------------------
# Forward all submitter's environment variables to the execution node
getenv = True

# ------------------------------------------------------------
# 5. Resources
# ------------------------------------------------------------
request_cpus = $(cpus)
request_memory = $(memory)
request_disk = $(disk)

# ------------------------------------------------------------
# 6. Input/Output files to transfer
# ------------------------------------------------------------
transfer_input_files = icsd, output/csv
transfer_output_files = output/root
transfer_output_remaps  = "root = output/root"
when_to_transfer_output = ON_EXIT
should_transfer_files = YES

# ------------------------------------------------------------
# 7. Queue definition
# ------------------------------------------------------------
queue physics, part_type, ion_z, ion_a, ion_q, energy_val, energy_unit, beam_on, geometry, geometry_method, voxel_val, voxel_unit, cpus, memory, disk from parameters.txt
