#/control/execute vis.mac
#/tracking/verbose 0
/run/printProgress 100
#/icsd/setGeom nanodosimeter
/icsd/setGeom StarTrack
/physics/setPhysics G4EmDNAPhysics_option2
/run/initialize

/gun/particle ion
/gun/ion 1 1 1
/gun/energy 20 MeV
/run/beamOn 10000

/gun/particle ion
/gun/ion 1 2 1
/gun/energy 16 MeV
/run/beamOn 10000

/gun/particle ion
/gun/ion 3 6 3
/gun/energy 20 MeV
/run/beamOn 10000

/gun/particle ion
/gun/ion 3 7 3
/gun/energy 26.7 MeV
/run/beamOn 1000
